name = "JCGEOutput"
uuid = "d375a7b0-530a-4732-94fc-3dc39a3a1ffd"
authors = ["Riccardo Boero <ribo@nilu.no>"]
version = "0.1.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JCGECalibrate = "52bcf1bb-5715-4bdb-b809-8ade53bb6205"
JCGECore = "9fb9d605-0ed3-4980-82c1-f0874844db5d"
JCGERuntime = "cc244198-1562-43f7-ad75-589e1d675269"
DualSignals = "e4247b8d-50b5-41ef-b53d-f6e21a6bdac0"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
JCGECore = { url = "https://github.com/equicirco/JCGECore.jl" }
JCGECalibrate = { url = "https://github.com/equicirco/JCGECalibrate.jl" }
JCGERuntime = { url = "https://github.com/equicirco/JCGERuntime.jl" }

[compat]
Arrow = "2"
CSV = "0.10"
DualSignals = "0.1"
JCGECalibrate = "0.1"
JCGECore = "0.1"
JCGERuntime = "0.1"
JSON3 = "1"
JuMP = "1"
Parquet = "0.8"
Tables = "1"
julia = "1.10"
